# Generated by Django 5.0.9 on 2024-11-22 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AreaObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(blank=True, null=True)),
                ('object_latitude', models.CharField(max_length=255)),
                ('object_longitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('distance_sum', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AreaObjectFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
                ('area_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_associations', to='navigation.areaobject')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_latitude', models.IntegerField()),
                ('object_longitude', models.IntegerField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='navigation.areaobject')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deans_office_number', models.CharField(max_length=255)),
                ('area_objects', models.ManyToManyField(related_name='faculties', through='navigation.AreaObjectFaculty', to='navigation.areaobject')),
            ],
        ),
        migrations.AddField(
            model_name='areaobjectfaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_object_associations', to='navigation.faculty'),
        ),
        migrations.CreateModel(
            name='ImportantPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_place', to='navigation.areaobject')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute', to='navigation.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to='navigation.address')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to='navigation.guide')),
            ],
        ),
        migrations.AddField(
            model_name='areaobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_objects', to='navigation.object'),
        ),
        migrations.CreateModel(
            name='PointObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_category', models.CharField(max_length=255)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('object_latitude', models.CharField(max_length=255)),
                ('object_longitude', models.CharField(max_length=255)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_objects', to='navigation.object')),
            ],
        ),
        migrations.CreateModel(
            name='UserObjectSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_latitude', models.CharField(max_length=255)),
                ('object_longitude', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('route_created_count', models.IntegerField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_search', to='navigation.object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_search', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
