# Generated by Django 5.0.9 on 2024-11-12 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AreaObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('is_paid', models.BooleanField()),
                ('object_latitude', models.CharField(max_length=255)),
                ('object_longitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AreaObjectFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=255)),
                ('area_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_associations', to='navigation.areaobject')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_latitude', models.IntegerField()),
                ('object_longitude', models.IntegerField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='navigation.areaobject')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('deans_office_number', models.CharField(max_length=255)),
                ('area_objects', models.ManyToManyField(related_name='faculties', through='navigation.AreaObjectFaculty', to='navigation.areaobject')),
            ],
        ),
        migrations.AddField(
            model_name='areaobjectfaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_object_associations', to='navigation.faculty'),
        ),
        migrations.CreateModel(
            name='ImportantPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('room', models.CharField(max_length=255)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_place', to='navigation.areaobject')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute', to='navigation.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to='navigation.address')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to='navigation.guide')),
            ],
        ),
        migrations.AddField(
            model_name='areaobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_objects', to='navigation.object'),
        ),
        migrations.CreateModel(
            name='PointObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_category', models.CharField(max_length=255)),
                ('event_start', models.DateTimeField(null=True)),
                ('event_end', models.DateTimeField(null=True)),
                ('object_latitude', models.CharField(max_length=255)),
                ('object_longitude', models.CharField(max_length=255)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_objects', to='navigation.object')),
            ],
        ),
        migrations.CreateModel(
            name='UserObjectSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_latitude', models.CharField(max_length=255)),
                ('object_longitude', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('routeCreatedCount', models.IntegerField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_search', to='navigation.object')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_search', to='navigation.user')),
            ],
        ),
    ]
