name: Build and deploy Python app to Azure Web App
on:
  push:
    branches: [ "devops/test-build-pipeline" ]
  workflow_dispatch:

permissions:
  contents: none

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'dev-api'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
          cache: 'pip'
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt  # Instalacja zależności
          python3 --version
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'dev-api'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
